<!-- TRECHO QUE FAZ O DASHBOARD FUNCIONAR (LEMBRE-SE QUE EXISTE UM CSS NO /PUBLIC NECESSARIO*/ -->   
<script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <figure class="highcharts-figure">
      <div id="container7"></div>
      
    </figure>
  <?php
    $chamadosPorCliente = $chamadosAssumidosSLA->calculaQtChamadosPorCliente();
  ?>
<script>
Highcharts.chart('container7', {
  chart: {
    type: 'line'
  },
  title: {
    text: 'Total de chamados por Cliente'
  },
  xAxis: {
    categories: ['Jan/<?php echo date("Y")?>', 'Fev/<?php echo date("Y")?>', 'Mar/<?php echo date("Y")?>', 'Abr/<?php echo date("Y")?>', 'Mai/<?php echo date("Y")?>', 'Jun/<?php echo date("Y")?>', 'Jul/<?php echo date("Y")?>', 'Ago/<?php echo date("Y")?>', 'Set/<?php echo date("Y")?>', 'Out/<?php echo date("Y")?>', 'Nov/<?php echo date("Y")?>', 'Dez/<?php echo date("Y")?>']
  },
  yAxis: {
    title: {
      text: 'Quantidade'
    }
  },
  plotOptions: {
    line: {
      dataLabels: {
        enabled: true
      },
      enableMouseTracking: false
    }
  },
  series: [{
    name: 'BGN',
    data: [<?php if(isset($chamadosPorCliente[1][5])) {echo $chamadosPorCliente[1][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][5])) {echo $chamadosPorCliente[2][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][5])) {echo $chamadosPorCliente[3][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][5])) {echo $chamadosPorCliente[4][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][5])) {echo $chamadosPorCliente[5][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][5])) {echo $chamadosPorCliente[6][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][5])) {echo $chamadosPorCliente[7][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][5])) {echo $chamadosPorCliente[8][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][5])) {echo $chamadosPorCliente[9][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][5])) {echo $chamadosPorCliente[10][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][5])) {echo $chamadosPorCliente[11][5];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][5])) {echo $chamadosPorCliente[12][5];} else { echo '0';}?>]
  },{
    name: 'Clinipam',
    data: [<?php if(isset($chamadosPorCliente[1][6])) {echo $chamadosPorCliente[1][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][6])) {echo $chamadosPorCliente[2][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][6])) {echo $chamadosPorCliente[3][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][6])) {echo $chamadosPorCliente[4][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][6])) {echo $chamadosPorCliente[5][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][6])) {echo $chamadosPorCliente[6][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][6])) {echo $chamadosPorCliente[7][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][6])) {echo $chamadosPorCliente[8][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][6])) {echo $chamadosPorCliente[9][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][6])) {echo $chamadosPorCliente[10][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][6])) {echo $chamadosPorCliente[11][6];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][6])) {echo $chamadosPorCliente[12][6];} else { echo '0';}?>]
  },{
    name: 'Executiva',
    data: [<?php if(isset($chamadosPorCliente[1][13])) {echo $chamadosPorCliente[1][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][13])) {echo $chamadosPorCliente[2][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][13])) {echo $chamadosPorCliente[3][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][13])) {echo $chamadosPorCliente[4][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][13])) {echo $chamadosPorCliente[5][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][13])) {echo $chamadosPorCliente[6][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][13])) {echo $chamadosPorCliente[7][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][13])) {echo $chamadosPorCliente[8][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][13])) {echo $chamadosPorCliente[9][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][13])) {echo $chamadosPorCliente[10][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][13])) {echo $chamadosPorCliente[11][13];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][13])) {echo $chamadosPorCliente[12][13];} else { echo '0';}?>]
  },{
    name: 'Fast',
    data: [<?php if(isset($chamadosPorCliente[1][14])) {echo $chamadosPorCliente[1][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][14])) {echo $chamadosPorCliente[2][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][14])) {echo $chamadosPorCliente[3][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][14])) {echo $chamadosPorCliente[4][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][14])) {echo $chamadosPorCliente[5][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][14])) {echo $chamadosPorCliente[6][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][14])) {echo $chamadosPorCliente[7][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][14])) {echo $chamadosPorCliente[8][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][14])) {echo $chamadosPorCliente[9][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][14])) {echo $chamadosPorCliente[10][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][14])) {echo $chamadosPorCliente[11][14];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][14])) {echo $chamadosPorCliente[12][14];} else { echo '0';}?>]
  },{
    name: 'G3',
    data: [<?php if(isset($chamadosPorCliente[1][16])) {echo $chamadosPorCliente[1][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][16])) {echo $chamadosPorCliente[2][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][16])) {echo $chamadosPorCliente[3][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][16])) {echo $chamadosPorCliente[4][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][16])) {echo $chamadosPorCliente[5][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][16])) {echo $chamadosPorCliente[6][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][16])) {echo $chamadosPorCliente[7][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][16])) {echo $chamadosPorCliente[8][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][16])) {echo $chamadosPorCliente[9][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][16])) {echo $chamadosPorCliente[10][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][16])) {echo $chamadosPorCliente[11][16];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][16])) {echo $chamadosPorCliente[12][16];} else { echo '0';}?>]
  },{
    name: 'HC2',
    data: [<?php if(isset($chamadosPorCliente[1][17])) {echo $chamadosPorCliente[1][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][17])) {echo $chamadosPorCliente[2][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][17])) {echo $chamadosPorCliente[3][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][17])) {echo $chamadosPorCliente[4][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][17])) {echo $chamadosPorCliente[5][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][17])) {echo $chamadosPorCliente[6][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][17])) {echo $chamadosPorCliente[7][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][17])) {echo $chamadosPorCliente[8][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][17])) {echo $chamadosPorCliente[9][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][17])) {echo $chamadosPorCliente[10][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][17])) {echo $chamadosPorCliente[11][17];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][17])) {echo $chamadosPorCliente[12][17];} else { echo '0';}?>]
  },{
    name: 'Hipercob',
    data: [<?php if(isset($chamadosPorCliente[1][18])) {echo $chamadosPorCliente[1][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][18])) {echo $chamadosPorCliente[2][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][18])) {echo $chamadosPorCliente[3][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][18])) {echo $chamadosPorCliente[4][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][18])) {echo $chamadosPorCliente[5][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][18])) {echo $chamadosPorCliente[6][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][18])) {echo $chamadosPorCliente[7][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][18])) {echo $chamadosPorCliente[8][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][18])) {echo $chamadosPorCliente[9][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][18])) {echo $chamadosPorCliente[10][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][18])) {echo $chamadosPorCliente[11][18];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][18])) {echo $chamadosPorCliente[12][18];} else { echo '0';}?>]
  },{
    name: 'Nacional',
    data: [<?php if(isset($chamadosPorCliente[1][23])) {echo $chamadosPorCliente[1][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][23])) {echo $chamadosPorCliente[2][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][23])) {echo $chamadosPorCliente[3][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][23])) {echo $chamadosPorCliente[4][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][23])) {echo $chamadosPorCliente[5][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][23])) {echo $chamadosPorCliente[6][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][23])) {echo $chamadosPorCliente[7][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][23])) {echo $chamadosPorCliente[8][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][23])) {echo $chamadosPorCliente[9][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][23])) {echo $chamadosPorCliente[10][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][23])) {echo $chamadosPorCliente[11][23];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][23])) {echo $chamadosPorCliente[12][23];} else { echo '0';}?>]
  },{
    name: 'Saes',
    data: [<?php if(isset($chamadosPorCliente[1][26])) {echo $chamadosPorCliente[1][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][26])) {echo $chamadosPorCliente[2][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][26])) {echo $chamadosPorCliente[3][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][26])) {echo $chamadosPorCliente[4][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][26])) {echo $chamadosPorCliente[5][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][26])) {echo $chamadosPorCliente[6][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][26])) {echo $chamadosPorCliente[7][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][26])) {echo $chamadosPorCliente[8][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][26])) {echo $chamadosPorCliente[9][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][26])) {echo $chamadosPorCliente[10][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][26])) {echo $chamadosPorCliente[11][26];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][26])) {echo $chamadosPorCliente[12][26];} else { echo '0';}?>]
  },{
    name: 'Saty',
    data: [<?php if(isset($chamadosPorCliente[1][28])) {echo $chamadosPorCliente[1][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][28])) {echo $chamadosPorCliente[2][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][28])) {echo $chamadosPorCliente[3][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][28])) {echo $chamadosPorCliente[4][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][28])) {echo $chamadosPorCliente[5][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][28])) {echo $chamadosPorCliente[6][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][28])) {echo $chamadosPorCliente[7][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][28])) {echo $chamadosPorCliente[8][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][28])) {echo $chamadosPorCliente[9][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][28])) {echo $chamadosPorCliente[10][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][28])) {echo $chamadosPorCliente[11][28];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][28])) {echo $chamadosPorCliente[12][28];} else { echo '0';}?>]
  },{
    name: 'Senff',
    data: [<?php if(isset($chamadosPorCliente[1][29])) {echo $chamadosPorCliente[1][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][29])) {echo $chamadosPorCliente[2][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][29])) {echo $chamadosPorCliente[3][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][29])) {echo $chamadosPorCliente[4][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][29])) {echo $chamadosPorCliente[5][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][29])) {echo $chamadosPorCliente[6][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][29])) {echo $chamadosPorCliente[7][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][29])) {echo $chamadosPorCliente[8][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][29])) {echo $chamadosPorCliente[9][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][29])) {echo $chamadosPorCliente[10][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][29])) {echo $chamadosPorCliente[11][29];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][29])) {echo $chamadosPorCliente[12][29];} else { echo '0';}?>]
  },{
    name: 'Gigatec',
    data: [<?php if(isset($chamadosPorCliente[1][30])) {echo $chamadosPorCliente[1][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][30])) {echo $chamadosPorCliente[2][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][30])) {echo $chamadosPorCliente[3][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][30])) {echo $chamadosPorCliente[4][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][30])) {echo $chamadosPorCliente[5][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][30])) {echo $chamadosPorCliente[6][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][30])) {echo $chamadosPorCliente[7][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][30])) {echo $chamadosPorCliente[8][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][30])) {echo $chamadosPorCliente[9][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][30])) {echo $chamadosPorCliente[10][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][30])) {echo $chamadosPorCliente[11][30];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][30])) {echo $chamadosPorCliente[12][30];} else { echo '0';}?>]
  },{
    name: 'SisBracon',
    data: [<?php if(isset($chamadosPorCliente[1][31])) {echo $chamadosPorCliente[1][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][31])) {echo $chamadosPorCliente[2][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][31])) {echo $chamadosPorCliente[3][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][31])) {echo $chamadosPorCliente[4][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][31])) {echo $chamadosPorCliente[5][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][31])) {echo $chamadosPorCliente[6][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][31])) {echo $chamadosPorCliente[7][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][31])) {echo $chamadosPorCliente[8][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][31])) {echo $chamadosPorCliente[9][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][31])) {echo $chamadosPorCliente[10][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][31])) {echo $chamadosPorCliente[11][31];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][31])) {echo $chamadosPorCliente[12][31];} else { echo '0';}?>]
  },{
    name: 'Solut',
    data: [<?php if(isset($chamadosPorCliente[1][32])) {echo $chamadosPorCliente[1][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][32])) {echo $chamadosPorCliente[2][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][32])) {echo $chamadosPorCliente[3][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][32])) {echo $chamadosPorCliente[4][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][32])) {echo $chamadosPorCliente[5][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][32])) {echo $chamadosPorCliente[6][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][32])) {echo $chamadosPorCliente[7][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][32])) {echo $chamadosPorCliente[8][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][32])) {echo $chamadosPorCliente[9][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][32])) {echo $chamadosPorCliente[10][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][32])) {echo $chamadosPorCliente[11][32];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][32])) {echo $chamadosPorCliente[12][32];} else { echo '0';}?>]
  },{
    name: 'Speedy',
    data: [<?php if(isset($chamadosPorCliente[1][33])) {echo $chamadosPorCliente[1][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][33])) {echo $chamadosPorCliente[2][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][33])) {echo $chamadosPorCliente[3][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][33])) {echo $chamadosPorCliente[4][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][33])) {echo $chamadosPorCliente[5][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][33])) {echo $chamadosPorCliente[6][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][33])) {echo $chamadosPorCliente[7][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][33])) {echo $chamadosPorCliente[8][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][33])) {echo $chamadosPorCliente[9][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][33])) {echo $chamadosPorCliente[10][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][33])) {echo $chamadosPorCliente[11][33];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][33])) {echo $chamadosPorCliente[12][33];} else { echo '0';}?>]
  },{
    name: 'TopOne',
    data: [<?php if(isset($chamadosPorCliente[1][34])) {echo $chamadosPorCliente[1][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][34])) {echo $chamadosPorCliente[2][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][34])) {echo $chamadosPorCliente[3][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][34])) {echo $chamadosPorCliente[4][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][34])) {echo $chamadosPorCliente[5][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][34])) {echo $chamadosPorCliente[6][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][34])) {echo $chamadosPorCliente[7][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][34])) {echo $chamadosPorCliente[8][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][34])) {echo $chamadosPorCliente[9][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][34])) {echo $chamadosPorCliente[10][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][34])) {echo $chamadosPorCliente[11][34];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][34])) {echo $chamadosPorCliente[12][34];} else { echo '0';}?>]
  },{
    name: 'Unicobra',
    data: [<?php if(isset($chamadosPorCliente[1][36])) {echo $chamadosPorCliente[1][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][36])) {echo $chamadosPorCliente[2][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][36])) {echo $chamadosPorCliente[3][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][36])) {echo $chamadosPorCliente[4][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][36])) {echo $chamadosPorCliente[5][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][36])) {echo $chamadosPorCliente[6][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][36])) {echo $chamadosPorCliente[7][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][36])) {echo $chamadosPorCliente[8][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][36])) {echo $chamadosPorCliente[9][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][36])) {echo $chamadosPorCliente[10][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][36])) {echo $chamadosPorCliente[11][36];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][36])) {echo $chamadosPorCliente[12][36];} else { echo '0';}?>]
  },{
    name: 'SJP',
    data: [<?php if(isset($chamadosPorCliente[1][41])) {echo $chamadosPorCliente[1][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][41])) {echo $chamadosPorCliente[2][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][41])) {echo $chamadosPorCliente[3][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][41])) {echo $chamadosPorCliente[4][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][41])) {echo $chamadosPorCliente[5][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][41])) {echo $chamadosPorCliente[6][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][41])) {echo $chamadosPorCliente[7][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][41])) {echo $chamadosPorCliente[8][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][41])) {echo $chamadosPorCliente[9][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][41])) {echo $chamadosPorCliente[10][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][41])) {echo $chamadosPorCliente[11][41];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][41])) {echo $chamadosPorCliente[12][41];} else { echo '0';}?>]
  },{
    name: 'Level',
    data: [<?php if(isset($chamadosPorCliente[1][42])) {echo $chamadosPorCliente[1][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][42])) {echo $chamadosPorCliente[2][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][42])) {echo $chamadosPorCliente[3][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][42])) {echo $chamadosPorCliente[4][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][42])) {echo $chamadosPorCliente[5][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][42])) {echo $chamadosPorCliente[6][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][42])) {echo $chamadosPorCliente[7][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][42])) {echo $chamadosPorCliente[8][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][42])) {echo $chamadosPorCliente[9][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][42])) {echo $chamadosPorCliente[10][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][42])) {echo $chamadosPorCliente[11][42];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][42])) {echo $chamadosPorCliente[12][42];} else { echo '0';}?>]
  },{
    name: 'AcerteAqui',
    data: [<?php if(isset($chamadosPorCliente[1][45])) {echo $chamadosPorCliente[1][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][45])) {echo $chamadosPorCliente[2][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][45])) {echo $chamadosPorCliente[3][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][45])) {echo $chamadosPorCliente[4][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][45])) {echo $chamadosPorCliente[5][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][45])) {echo $chamadosPorCliente[6][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][45])) {echo $chamadosPorCliente[7][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[8][45])) {echo $chamadosPorCliente[8][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][45])) {echo $chamadosPorCliente[9][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][45])) {echo $chamadosPorCliente[10][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][45])) {echo $chamadosPorCliente[11][45];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][45])) {echo $chamadosPorCliente[12][45];} else { echo '0';}?>]
  },
]});

<?php 
/*{
    name: 'AqiX',
    data: [<?php if(isset($chamadosPorCliente[1][3])) {echo $chamadosPorCliente[1][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][3])) {echo $chamadosPorCliente[2][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][3])) {echo $chamadosPorCliente[3][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][3])) {echo $chamadosPorCliente[4][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][3])) {echo $chamadosPorCliente[5][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][3])) {echo $chamadosPorCliente[6][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][3])) {echo $chamadosPorCliente[7][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][3])) {echo $chamadosPorCliente[6][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][3])) {echo $chamadosPorCliente[9][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][3])) {echo $chamadosPorCliente[10][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][3])) {echo $chamadosPorCliente[11][3];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][3])) {echo $chamadosPorCliente[12][3];} else { echo '0';}?>]
  },{
    name: 'Connect',
    data: [<?php if(isset($chamadosPorCliente[1][8])) {echo $chamadosPorCliente[1][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][8])) {echo $chamadosPorCliente[2][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][8])) {echo $chamadosPorCliente[3][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][8])) {echo $chamadosPorCliente[4][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][8])) {echo $chamadosPorCliente[5][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][8])) {echo $chamadosPorCliente[6][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][8])) {echo $chamadosPorCliente[7][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][8])) {echo $chamadosPorCliente[6][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][8])) {echo $chamadosPorCliente[9][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][8])) {echo $chamadosPorCliente[10][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][8])) {echo $chamadosPorCliente[11][8];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][8])) {echo $chamadosPorCliente[12][8];} else { echo '0';}?>]
  },{
    name: 'CRX',
    data: [<?php if(isset($chamadosPorCliente[1][9])) {echo $chamadosPorCliente[1][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][9])) {echo $chamadosPorCliente[2][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][9])) {echo $chamadosPorCliente[3][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][9])) {echo $chamadosPorCliente[4][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][9])) {echo $chamadosPorCliente[5][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][9])) {echo $chamadosPorCliente[6][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][9])) {echo $chamadosPorCliente[7][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][9])) {echo $chamadosPorCliente[6][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][9])) {echo $chamadosPorCliente[9][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][9])) {echo $chamadosPorCliente[10][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][9])) {echo $chamadosPorCliente[11][9];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][9])) {echo $chamadosPorCliente[12][9];} else { echo '0';}?>]
  },{
    name: 'Finner',
    data: [<?php if(isset($chamadosPorCliente[1][15])) {echo $chamadosPorCliente[1][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][15])) {echo $chamadosPorCliente[2][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][15])) {echo $chamadosPorCliente[3][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][15])) {echo $chamadosPorCliente[4][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][15])) {echo $chamadosPorCliente[5][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][15])) {echo $chamadosPorCliente[6][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][15])) {echo $chamadosPorCliente[7][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][15])) {echo $chamadosPorCliente[6][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][15])) {echo $chamadosPorCliente[9][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][15])) {echo $chamadosPorCliente[10][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][15])) {echo $chamadosPorCliente[11][15];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][15])) {echo $chamadosPorCliente[12][15];} else { echo '0';}?>]
  },{
    name: 'Inter',
    data: [<?php if(isset($chamadosPorCliente[1][19])) {echo $chamadosPorCliente[1][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][19])) {echo $chamadosPorCliente[2][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][19])) {echo $chamadosPorCliente[3][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][19])) {echo $chamadosPorCliente[4][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][19])) {echo $chamadosPorCliente[5][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][19])) {echo $chamadosPorCliente[6][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][19])) {echo $chamadosPorCliente[7][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][19])) {echo $chamadosPorCliente[6][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][19])) {echo $chamadosPorCliente[9][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][19])) {echo $chamadosPorCliente[10][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][19])) {echo $chamadosPorCliente[11][19];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][19])) {echo $chamadosPorCliente[12][19];} else { echo '0';}?>]
  },{
    name: 'M.Oliver',
    data: [<?php if(isset($chamadosPorCliente[1][21])) {echo $chamadosPorCliente[1][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][21])) {echo $chamadosPorCliente[2][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][21])) {echo $chamadosPorCliente[3][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][21])) {echo $chamadosPorCliente[4][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][21])) {echo $chamadosPorCliente[5][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][21])) {echo $chamadosPorCliente[6][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][21])) {echo $chamadosPorCliente[7][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][21])) {echo $chamadosPorCliente[6][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][21])) {echo $chamadosPorCliente[9][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][21])) {echo $chamadosPorCliente[10][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][21])) {echo $chamadosPorCliente[11][21];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][21])) {echo $chamadosPorCliente[12][21];} else { echo '0';}?>]
  },{
    name: 'MasterCob',
    data: [<?php if(isset($chamadosPorCliente[1][22])) {echo $chamadosPorCliente[1][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][22])) {echo $chamadosPorCliente[2][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][22])) {echo $chamadosPorCliente[3][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][22])) {echo $chamadosPorCliente[4][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][22])) {echo $chamadosPorCliente[5][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][22])) {echo $chamadosPorCliente[6][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][22])) {echo $chamadosPorCliente[7][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][22])) {echo $chamadosPorCliente[6][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][22])) {echo $chamadosPorCliente[9][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][22])) {echo $chamadosPorCliente[10][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][22])) {echo $chamadosPorCliente[11][22];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][22])) {echo $chamadosPorCliente[12][22];} else { echo '0';}?>]
  },{
    name: 'Total',
    data: [<?php if(isset($chamadosPorCliente[1][35])) {echo $chamadosPorCliente[1][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][35])) {echo $chamadosPorCliente[2][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][35])) {echo $chamadosPorCliente[3][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][35])) {echo $chamadosPorCliente[4][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][35])) {echo $chamadosPorCliente[5][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][35])) {echo $chamadosPorCliente[6][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][35])) {echo $chamadosPorCliente[7][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][35])) {echo $chamadosPorCliente[6][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][35])) {echo $chamadosPorCliente[9][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][35])) {echo $chamadosPorCliente[10][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][35])) {echo $chamadosPorCliente[11][35];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][35])) {echo $chamadosPorCliente[12][35];} else { echo '0';}?>]
  },{
    name: 'Uol',
    data: [<?php if(isset($chamadosPorCliente[1][38])) {echo $chamadosPorCliente[1][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][38])) {echo $chamadosPorCliente[2][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][38])) {echo $chamadosPorCliente[3][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][38])) {echo $chamadosPorCliente[4][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][38])) {echo $chamadosPorCliente[5][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][38])) {echo $chamadosPorCliente[6][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][38])) {echo $chamadosPorCliente[7][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][38])) {echo $chamadosPorCliente[6][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][38])) {echo $chamadosPorCliente[9][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][38])) {echo $chamadosPorCliente[10][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][38])) {echo $chamadosPorCliente[11][38];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][38])) {echo $chamadosPorCliente[12][38];} else { echo '0';}?>]
  },{
    name: 'Valor',
    data: [<?php if(isset($chamadosPorCliente[1][40])) {echo $chamadosPorCliente[1][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][40])) {echo $chamadosPorCliente[2][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][40])) {echo $chamadosPorCliente[3][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][40])) {echo $chamadosPorCliente[4][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][40])) {echo $chamadosPorCliente[5][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][40])) {echo $chamadosPorCliente[6][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][40])) {echo $chamadosPorCliente[7][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][40])) {echo $chamadosPorCliente[6][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][40])) {echo $chamadosPorCliente[9][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][40])) {echo $chamadosPorCliente[10][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][40])) {echo $chamadosPorCliente[11][40];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][40])) {echo $chamadosPorCliente[12][40];} else { echo '0';}?>]
  },{
    name: 'VNCA',
    data: [<?php if(isset($chamadosPorCliente[1][43])) {echo $chamadosPorCliente[1][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[2][43])) {echo $chamadosPorCliente[2][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[3][43])) {echo $chamadosPorCliente[3][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[4][43])) {echo $chamadosPorCliente[4][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[5][43])) {echo $chamadosPorCliente[5][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][43])) {echo $chamadosPorCliente[6][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[7][43])) {echo $chamadosPorCliente[7][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[6][43])) {echo $chamadosPorCliente[6][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[9][43])) {echo $chamadosPorCliente[9][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[10][43])) {echo $chamadosPorCliente[10][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[11][43])) {echo $chamadosPorCliente[11][43];} else { echo '0';}?>, <?php if(isset($chamadosPorCliente[12][43])) {echo $chamadosPorCliente[12][43];} else { echo '0';}?>]
  },
  */

  ?>
</script>